### ISSUE TITLE
Can we generate attributions and Removal effects without 'Start' state

### ISSUE THREAD

**Issue by naadvar** [kailin-lu/markovattribution#1]
Hello ,

I am currently trying to model a Marketing Multi-Channel Attribution. All the articles and the packages I have come across use a special "start" state and the removal effect is calculated based on that start state

My question primarily is of two parts:

1. Can we consider the first touch as the start state of each path.
2. How can we calculate the removal effect if there is no "start "state( any documentation or an explanation of the formula would be really helpful)

**Comment by kailin-lu** [comment]
Hi @naadvar, 

The 'start' state can be thought of as a placeholder indicating the beginning of a conversion path. If we prepend all conversion paths with 'start' we can calculate the probability of an average conversion path to end in a conversion or a non-conversion ('null') state. This is because we are assuming that conversion paths can be modeled as an absorbing Markov chain - all paths must end with either a conversion or a non-conversion. 

If we were to remove the 'start' state, we could calculate the probability of conversion given that a user starts their path at a given channel. However, we would not be able to calculate a removal effect based on the definition given in the original paper. 

Removal effect of channel _x_ := 1 - (probability of conversion without visits to channel _x_  / probability of conversion given that someone has started a conversion path) 

In plain terms, the removal effect of channel _x_ is the percentage of conversions which would not have occurred if visits to channel _x_ were not possible all else equal. This is **not** the same value as the percentage of conversions which would not have occurred without channel _x_ existing _and_ starting at a specific channel _y_. 

Adding a start state to conversion paths is also straightforward - you can insert a channel called 'start' at the beginning of each one of your conversion paths prior to the first channel visited.
